owner: pabio-status
repo: production
sites:
  - name: Pabio.com
    url: https://pabio.com
  - name: Pabio API
    url: https://pabioapi.com/health
status-website:
  cname: pabiostatus.com
  logoUrl: https://github.com/pabio-status/production/raw/HEAD/assets/logo.svg
  name: Pabio Status
  navbar:
    - title: Status
      href: /
    - title: Pabio.com
      href: https://pabio.com
